### PR TITLE
Plot Merge Beta

### PR DESCRIPTION
**Pull request by jasonwynn10**
## Introduction
Introducing Plot Merge Beta

### Relevant issues

#59

### API changes

Merge API has been added. New fields exist to differentiate between merged checks versus normal checks.

### Behavioral changes

Untested

## Backwards compatibility

Not Yet Verified

## Tests

N/A

### CODE REVIEW

**Comment by benda95280** [comment]
Any News ? :(

**Comment by benda95280** [comment]
@jasonwynn10 A big thanks 💘

**Comment by Wertzui123** [comment]
👍

**Pull request merged**
