### PR TITLE
Czech language updates

### PR DESCRIPTION
**Pull request by PikyCZ**
not completed

### CODE REVIEW

**Comment by PikyCZ** [comment]
full translate..

**Comment by Aericio** [comment]
wow, screw pullapprove.

**Comment by jasonwynn10** [comment]
+1

**Comment by jasonwynn10** [comment]
why did you rename the file?

**Comment by Aericio** [comment]
He undo-ed the rename.

**Comment by PikyCZ** [comment]
cze->czech  language / ces-??

**Comment by jasonwynn10** [comment]
@PikyCZ fair point

**Comment by jasonwynn10** [comment]
+1

**Pull request merged**
