### PR TITLE
fix generator

### PR DESCRIPTION
**Pull request by TDMidkwhatisxd**
That was so simple -_-  !

- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ ] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
{Type something here}

## Optional information
{Type something here}

### CODE REVIEW

**Comment by TDMidkwhatisxd** [comment]
No need thanks! Please test it before merging! Maybe i did some typo!

**Comment by jasonwynn10** [comment]
As previously stated, I plan on changing the way biomes are changed. The colors were the old method, but instead I will set the chunk biome's Id and resend the info to the client.

**Comment by TDMidkwhatisxd** [comment]
Ok! I use it on my server and world generated well, no errors in console!

**Comment by jasonwynn10** [comment]
I will have my biome if solution implemented by tomorrow. I have to finish repairing my computer first though

**Comment by Aericio** [comment]
jesus can we ban him

**Comment by Aericio** [comment]
@TDMidkwhatisxd stay at h4pm kid.

**Comment by TDMidkwhatisxd** [comment]
Ok! I wont help again!

**Comment by remotevase** [comment]
@Aericio, @TDMidkwhatisxd is a big help all around the github PE Community. Leave him be.

**Comment by Aericio** [comment]
@remotevase he is if he doesnt add "!" to every end of his sentence.

**Comment by remotevase** [comment]
Yes, I have noticed that too but I have managed to overlook it

**Comment by jasonwynn10** [comment]
OFF TOPIC

**Pull request closed without merging**
