### PR TITLE
Fixed place of SpoonDetector causing an error on initial startup

### PR DESCRIPTION
**Pull request by Sandertv**
… the plugin.

- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
{Type something here}

## Optional information
{Type something here}

Sorry for not filling out the template, such a small change shouldn't need it ;)

### CODE REVIEW

**Comment by Sandertv** [comment]
The formatting seems better to me now than before, just look carefully :P

**Comment by jasonwynn10** [comment]
I see spaces instead of tabs and extra indents
https://github.com/jasonwynn10/MyPlot/pull/74/files

**Comment by Sandertv** [comment]
I actually only used tabs. There were some spaces there already but I was too lazy to remove them... Okayyyy, I'll get PHPStorm to fix it up.

**Comment by Sandertv** [comment]
My bad, now I see it. GitHub web edit is more **** over than I thought.

**Comment by Sandertv** [comment]
Once again my reputation of countless commits for fixing a tiny thing 😄

**Comment by Sandertv** [comment]
Also fixes #69.

**Pull request merged**
