### PR TITLE
0.16 fix

### PR DESCRIPTION
**Pull request by TDMidkwhatisxd**
I already did this on 'my'  Myplot plugin and fixed the glich!
Why would u need this if u can use subcommands perms!

### CODE REVIEW

**Comment by jasonwynn10** [comment]
All it does is remove the permission setting though. That could cause an issue in the future for what I have planned.

**Comment by TDMidkwhatisxd** [comment]
Other perms work just fine! That is just useless :/ from my point ! Why would /p have perms?

**Comment by jasonwynn10** [comment]
I just changed the needed permission instead, does it work after I changed the plugin.yml file?

**Comment by TDMidkwhatisxd** [comment]
I dont know! I already have a working plots, so dont wanna to annoy players again!

**Comment by jasonwynn10** [comment]
Okay, i'm at my school atm so I can't test it

**Comment by jasonwynn10** [comment]
what's your server? I can add it to the readme as a tester

**Comment by TDMidkwhatisxd** [comment]
Is ok, i will test it on local ! :p

**Comment by TDMidkwhatisxd** [comment]
screenshot_2016-10-31-18-28-26

I just got a crash on /p list
Btw now /p work , i didnt know was from plugins.yml, i gave users permisions but it didnt work o-o !

**Comment by jasonwynn10** [comment]
can I get that crash dump file?

**Comment by TDMidkwhatisxd** [comment]
Do u still need it?

**Comment by jasonwynn10** [comment]
I guess not anymore. ima lock this now

**Comment by Aericio** [comment]
Note: you are using Elywing. We never tested it on that "fork" of Pocketmine.

**Comment by jasonwynn10** [comment]
this was already resolved

**Comment by Aericio** [comment]
I know, but just a note.

**Pull request closed without merging**
