### PR TITLE
(Spanish Lang) Rewritten everything from 0 and added the missing lines

### PR DESCRIPTION
**Pull request by UnEnanoMas**
I think it's time to update this

Don't blame me for not knowing how to use the pull req, I don't know what to put so I'll delete it

### CODE REVIEW

**Review by Wertzui123 — CHANGES_REQUESTED** [review]
https://github.com/UnEnanoMas/MyPlot/blob/patch-5/resources/spa.ini#L5
I think comments should remain English:
https://github.com/jasonwynn10/MyPlot/blob/master/resources/deu.ini#L5

**Comment by UnEnanoMas** [comment]
https://github.com/jasonwynn10/MyPlot/blob/master/resources/spa.ini

I only base myself on what was already written, if Jason approved it with comments in Spanish before, why not now?

@Wertzui123

**Comment by Wertzui123** [comment]
I don't know why he did this, but I think English would be better anyway.

**Comment by UnEnanoMas** [comment]
Nor does it affect anything that is in Spanish, I think it is silly to argue about this, the truth xd

**Comment by Aericio** [comment]
It should be fine to keep as @UnEnanoMas has it right now with the comments translated. We don't really need the English there to know what the strings are for, but the server owners editing the messages file may find it useful.

Whatever @jasonwynn10 thinks though /shrug

**Comment by Wertzui123** [comment]
I agree.

**Comment by UnEnanoMas** [comment]
Likewise, it makes no sense that someone who does not know Spanish is going to edit some of the Spanish language

https://i.pinimg.com/originals/50/6e/e2/506ee22b38ada4c5390498809fca404f.jpg

**Comment by jasonwynn10** [comment]
Leaving the comments in Spanish should be okay for users who want to use the custom lang file system

**Pull request merged**
